language: java
deploy:
  provider: releases
  api_key:
    secure: aD1Rnd8IHrON874vUmeuY3T3shXmdF7IvE6Pz6KQ0A2YWh18FApuQCKmY81NmgXWem4YIuSZ9HR6NJpVHlasCFM8uBeF08DtSUGXOJMGfavO8mu5ZYzLW4XUoevDN3umG3ATv3GHm9lbmZpU/D4uTb8SgcLAr9whSQphXtzzcfGrACHTxcuGCW8BpCO79t+TJx3rWarxH/cY0v6CQAAJzXUZqNgHsgwoZ0ED6XF7cJ+bARjyqWQ839NP1VdM728CnntQ0I+g5gSv1mKmKNaGkuOanEivyhe7kClCXwtamrPoLxVspJf5TqOzoyDO639dE4Pag/kkF/NsLtMBhCRfSNDJbY5R8fdRqDldhnRXNimysYcvLSozlkFp8mE95LzWr5FkrfE1p4DVVic3umu5+9MnoPFW+SpaH00th6I2AtWbBVR6VNFewHMnC8z4nFNBZJyri8gvt+F5cDgGDNpOQb7V97xFIC43P6wUKKwZr+zR4/zGB3U7UdBOapc0Kz8wNKI0233X5F5rHISdJ05biMfwOqKWY7xcvNkt74O9BeCv1E7f6DVZTqtYMWgUYNfM4ex5svs6fxKE36bjHdr4ZCu7cjJBXTk5ggfCuPuCCX5YcVGAWudzx2HNpTIF7hMqZHt9ijm8lZE2M6AQaQ78L2/Y/7mk4k/V0IE2AEowekU=
  skip_cleanup: true
  file_glob: true
  file: build/libs/alto-*-all.jar
  on:
    tags: true
